#### Challenge Engineer

In [84]:
import json
import datetime
import pandas as pd
from urllib import response
import requests

Conexion al enlace y exploración

In [85]:
url ='https://api.stackexchange.com/2.2/search?order=desc&sort=activity&intitle=perl&site=stackoverflow'
response = requests.get(url).json()
data=response["items"]
df=pd.json_normalize(data,max_level=1)
df.head()

,tags,is_answered,view_count,accepted_answer_id,answer_count,score,last_activity_date,creation_date,last_edit_date,question_id,...,title,owner.reputation,owner.user_id,owner.user_type,owner.profile_image,owner.display_name,owner.link,owner.accept_rate,closed_date,closed_reason
0,"[perl, hash]",True,28,73394813.0,1,0,1660796568,1660768898,1.660797e+09,73394676,...,How to print key value of hash reference in perl?,23,19028000,registered,https://lh3.googleusercontent.com/a-/AOh14Gh8z...,Jacob Berger,https://stackoverflow.com/users/19028000/jacob...,NaN,NaN,NaN
1,"[perl, sockets, fork, system, openssh]",True,254,NaN,2,1,1660768480,1466055541,1.558334e+09,37850684,...,Perl : implementing socket programming ( syste...,67,1814300,registered,https://www.gravatar.com/avatar/89276a0bf4a674...,hanish,https://stackoverflow.com/users/1814300/hanish,0.0,NaN,NaN
2,"[php, perl, sockets]",True,347,35617348.0,1,1,1660767941,1456367457,NaN,35617147,...,Send data from web server to perl socket listener,1439,4887464,registered,https://i.stack.imgur.com/InMEw.png?s=256&g=1,Olga Pshenichnikova,https://stackoverflow.com/users/4887464/olga-p...,100.0,NaN,NaN
3,"[regex, perl]",True,80,73377779.0,2,2,1660766297,1660663813,1.660664e+09,73376526,...,perl regex for matching multiline calls to c f...,5107,8710344,registered,https://www.gravatar.com/avatar/e2292c452c0d0c...,HardcoreHenry,https://stackoverflow.com/users/8710344/hardco...,80.0,NaN,NaN
4,[perl],True,63,73376046.0,1,0,1660759485,1660660897,1.660759e+09,73375876,...,Perl simple way to do multiple decision such a...,3975,10760768,registered,https://www.gravatar.com/avatar/c1655d01be2cdb...,Daniel Hao,https://stackoverflow.com/users/10760768/danie...,NaN,1.660665e+09,Opinion-based

Obtener el número de respuestas contestadas y no contestadas

In [86]:
respondidas = "Total de preguntas respondidas: " + str( df[df["is_answered"]==True]["is_answered"].count())
no_respondidas = "Total de preguntas no respondidas: " + str( df[df["is_answered"]==False]["is_answered"].count())
print(respondidas)
print(no_respondidas)

Total de preguntas respondidas: 24
Total de preguntas no respondidas: 6

Obtener la respuesta con menor número de vistas

In [87]:
df[df["view_count"]==df["view_count"].min()]

,tags,is_answered,view_count,accepted_answer_id,answer_count,score,last_activity_date,creation_date,last_edit_date,question_id,...,title,owner.reputation,owner.user_id,owner.user_type,owner.profile_image,owner.display_name,owner.link,owner.accept_rate,closed_date,closed_reason
29,"[c++, cmake, itk]",False,26,NaN,0,0,1660354359,1660354359,NaN,73341026,...,when cmake build ITK occur Perl Error in Windows,1,12641220,registered,https://lh3.googleusercontent.com/a-/AAuE7mAdq...,Richard,https://stackoverflow.com/users/12641220/richard,NaN,NaN,NaN

Obtener la respuesta más vieja y más actual

In [88]:
## Funcion para convertir la fecha en un formato correcto
def parseDate(date):
     fmt = "%Y-%m-%d %H:%M:%S"
     t_utc = datetime.datetime.utcfromtimestamp(float(date)/1000.)
     return t_utc.strftime(fmt)

In [89]:
df["creation_date"]=df["creation_date"].apply(parseDate)
df["last_activity_date"]=df["last_activity_date"].apply(parseDate)

In [95]:
df[df["creation_date"]==df["creation_date"].min()]

,tags,is_answered,view_count,accepted_answer_id,answer_count,score,last_activity_date,creation_date,last_edit_date,question_id,...,title,owner.reputation,owner.user_id,owner.user_type,owner.profile_image,owner.display_name,owner.link,owner.accept_rate,closed_date,closed_reason
14,"[perl, email, ssl, imap, attachment]",True,10649,2458024.0,4,7,1970-01-20 05:17:51,1970-01-15 16:25:35,1.269004e+09,2453548,...,How can I download IMAP mail attachments over ...,6849,146250,registered,https://www.gravatar.com/avatar/b7d1e3d8a7a3e8...,Space,https://stackoverflow.com/users/146250/space,97.0,NaN,NaN

In [91]:
df[df["creation_date"]==df["creation_date"].max()]

,tags,is_answered,view_count,accepted_answer_id,answer_count,score,last_activity_date,creation_date,last_edit_date,question_id,...,title,owner.reputation,owner.user_id,owner.user_type,owner.profile_image,owner.display_name,owner.link,owner.accept_rate,closed_date,closed_reason
0,"[perl, hash]",True,28,73394813.0,1,0,1970-01-20 05:19:56,1970-01-20 05:19:28,1.660797e+09,73394676,...,How to print key value of hash reference in perl?,23,19028000,registered,https://lh3.googleusercontent.com/a-/AOh14Gh8z...,Jacob Berger,https://stackoverflow.com/users/19028000/jacob...,NaN,NaN,NaN

Obtener la respuesta del owner que tenga una mayor reputación

In [92]:
df[df["owner.reputation"]==df["owner.reputation"].max()]

,tags,is_answered,view_count,accepted_answer_id,answer_count,score,last_activity_date,creation_date,last_edit_date,question_id,...,title,owner.reputation,owner.user_id,owner.user_type,owner.profile_image,owner.display_name,owner.link,owner.accept_rate,closed_date,closed_reason
26,"[perl, strace]",True,1268,9224678.0,2,2,1970-01-20 05:14:11,1970-01-16 09:07:39,1.660452e+09,9224396,...,How to find the current step the running perl ...,11657,673018,registered,https://www.gravatar.com/avatar/564a944115df18...,Mandar Pande,https://stackoverflow.com/users/673018/mandar-...,95.0,NaN,NaN